/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { Activity, Author, Book, CoverPhoto, User } from "../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const getApiV1Activities = (options?: AxiosRequestConfig): Promise<AxiosResponse<Activity[]>> => {
  return axios.default.get(`/api/v1/Activities`, options);
};

export const getGetApiV1ActivitiesQueryKey = () => {
  return [`/api/v1/Activities`] as const;
};

export const getGetApiV1ActivitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Activities>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Activities>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1ActivitiesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Activities>>> = ({ signal }) =>
    getApiV1Activities({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Activities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1ActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Activities>>>;
export type GetApiV1ActivitiesQueryError = AxiosError<unknown>;

export function useGetApiV1Activities<
  TData = Awaited<ReturnType<typeof getApiV1Activities>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Activities>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Activities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Activities>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Activities<
  TData = Awaited<ReturnType<typeof getApiV1Activities>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Activities>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Activities>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Activities>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Activities<
  TData = Awaited<ReturnType<typeof getApiV1Activities>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Activities>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1Activities<
  TData = Awaited<ReturnType<typeof getApiV1Activities>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Activities>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1ActivitiesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiV1Activities = (
  activity: Activity,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Activity>> => {
  return axios.default.post(`/api/v1/Activities`, activity, options);
};

export const getPostApiV1ActivitiesMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Activities>>, TError, { data: Activity }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Activities>>, TError, { data: Activity }, TContext> => {
  const mutationKey = ["postApiV1Activities"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Activities>>, { data: Activity }> = (props) => {
    const { data } = props ?? {};

    return postApiV1Activities(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1ActivitiesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Activities>>>;
export type PostApiV1ActivitiesMutationBody = Activity;
export type PostApiV1ActivitiesMutationError = AxiosError<unknown>;

export const usePostApiV1Activities = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1Activities>>,
      TError,
      { data: Activity },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiV1Activities>>, TError, { data: Activity }, TContext> => {
  return useMutation(getPostApiV1ActivitiesMutationOptions(options), queryClient);
};

export const getApiV1ActivitiesId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Activity>> => {
  return axios.default.get(`/api/v1/Activities/${id}`, options);
};

export const getGetApiV1ActivitiesIdQueryKey = (id: number) => {
  return [`/api/v1/Activities/${id}`] as const;
};

export const getGetApiV1ActivitiesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivitiesId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1ActivitiesIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1ActivitiesId>>> = ({ signal }) =>
    getApiV1ActivitiesId(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1ActivitiesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1ActivitiesId>>>;
export type GetApiV1ActivitiesIdQueryError = AxiosError<unknown>;

export function useGetApiV1ActivitiesId<
  TData = Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivitiesId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ActivitiesId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1ActivitiesId<
  TData = Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivitiesId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1ActivitiesId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1ActivitiesId<
  TData = Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivitiesId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1ActivitiesId<
  TData = Awaited<ReturnType<typeof getApiV1ActivitiesId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1ActivitiesId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1ActivitiesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiV1ActivitiesId = (
  id: number,
  activity: Activity,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Activity>> => {
  return axios.default.put(`/api/v1/Activities/${id}`, activity, options);
};

export const getPutApiV1ActivitiesIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1ActivitiesId>>,
    TError,
    { id: number; data: Activity },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1ActivitiesId>>,
  TError,
  { id: number; data: Activity },
  TContext
> => {
  const mutationKey = ["putApiV1ActivitiesId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1ActivitiesId>>,
    { id: number; data: Activity }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiV1ActivitiesId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1ActivitiesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1ActivitiesId>>>;
export type PutApiV1ActivitiesIdMutationBody = Activity;
export type PutApiV1ActivitiesIdMutationError = AxiosError<unknown>;

export const usePutApiV1ActivitiesId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1ActivitiesId>>,
      TError,
      { id: number; data: Activity },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1ActivitiesId>>,
  TError,
  { id: number; data: Activity },
  TContext
> => {
  return useMutation(getPutApiV1ActivitiesIdMutationOptions(options), queryClient);
};

export const deleteApiV1ActivitiesId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/Activities/${id}`, options);
};

export const getDeleteApiV1ActivitiesIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteApiV1ActivitiesId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteApiV1ActivitiesId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1ActivitiesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>>;

export type DeleteApiV1ActivitiesIdMutationError = AxiosError<unknown>;

export const useDeleteApiV1ActivitiesId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiV1ActivitiesId>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteApiV1ActivitiesIdMutationOptions(options), queryClient);
};

export const getApiV1Authors = (options?: AxiosRequestConfig): Promise<AxiosResponse<Author[]>> => {
  return axios.default.get(`/api/v1/Authors`, options);
};

export const getGetApiV1AuthorsQueryKey = () => {
  return [`/api/v1/Authors`] as const;
};

export const getGetApiV1AuthorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Authors>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Authors>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1AuthorsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Authors>>> = ({ signal }) =>
    getApiV1Authors({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Authors>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuthorsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Authors>>>;
export type GetApiV1AuthorsQueryError = AxiosError<unknown>;

export function useGetApiV1Authors<TData = Awaited<ReturnType<typeof getApiV1Authors>>, TError = AxiosError<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Authors>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Authors>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Authors>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Authors<TData = Awaited<ReturnType<typeof getApiV1Authors>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Authors>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Authors>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Authors>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Authors<TData = Awaited<ReturnType<typeof getApiV1Authors>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Authors>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1Authors<TData = Awaited<ReturnType<typeof getApiV1Authors>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Authors>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1AuthorsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiV1Authors = (author: Author, options?: AxiosRequestConfig): Promise<AxiosResponse<Author>> => {
  return axios.default.post(`/api/v1/Authors`, author, options);
};

export const getPostApiV1AuthorsMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Authors>>, TError, { data: Author }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Authors>>, TError, { data: Author }, TContext> => {
  const mutationKey = ["postApiV1Authors"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Authors>>, { data: Author }> = (props) => {
    const { data } = props ?? {};

    return postApiV1Authors(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1AuthorsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Authors>>>;
export type PostApiV1AuthorsMutationBody = Author;
export type PostApiV1AuthorsMutationError = AxiosError<unknown>;

export const usePostApiV1Authors = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Authors>>, TError, { data: Author }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiV1Authors>>, TError, { data: Author }, TContext> => {
  return useMutation(getPostApiV1AuthorsMutationOptions(options), queryClient);
};

export const getApiV1AuthorsAuthorsBooksIdBook = (
  idBook: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Author[]>> => {
  return axios.default.get(`/api/v1/Authors/authors/books/${idBook}`, options);
};

export const getGetApiV1AuthorsAuthorsBooksIdBookQueryKey = (idBook: number) => {
  return [`/api/v1/Authors/authors/books/${idBook}`] as const;
};

export const getGetApiV1AuthorsAuthorsBooksIdBookQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1AuthorsAuthorsBooksIdBookQueryKey(idBook);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>> = ({ signal }) =>
    getApiV1AuthorsAuthorsBooksIdBook(idBook, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!idBook, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuthorsAuthorsBooksIdBookQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>
>;
export type GetApiV1AuthorsAuthorsBooksIdBookQueryError = AxiosError<unknown>;

export function useGetApiV1AuthorsAuthorsBooksIdBook<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1AuthorsAuthorsBooksIdBook<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1AuthorsAuthorsBooksIdBook<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1AuthorsAuthorsBooksIdBook<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsAuthorsBooksIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1AuthorsAuthorsBooksIdBookQueryOptions(idBook, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiV1AuthorsId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Author>> => {
  return axios.default.get(`/api/v1/Authors/${id}`, options);
};

export const getGetApiV1AuthorsIdQueryKey = (id: number) => {
  return [`/api/v1/Authors/${id}`] as const;
};

export const getGetApiV1AuthorsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1AuthorsId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1AuthorsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthorsId>>> = ({ signal }) =>
    getApiV1AuthorsId(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1AuthorsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuthorsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthorsId>>>;
export type GetApiV1AuthorsIdQueryError = AxiosError<unknown>;

export function useGetApiV1AuthorsId<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthorsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthorsId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1AuthorsId<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthorsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthorsId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1AuthorsId<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1AuthorsId<
  TData = Awaited<ReturnType<typeof getApiV1AuthorsId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthorsId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1AuthorsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiV1AuthorsId = (
  id: number,
  author: Author,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Author>> => {
  return axios.default.put(`/api/v1/Authors/${id}`, author, options);
};

export const getPutApiV1AuthorsIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1AuthorsId>>,
    TError,
    { id: number; data: Author },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1AuthorsId>>,
  TError,
  { id: number; data: Author },
  TContext
> => {
  const mutationKey = ["putApiV1AuthorsId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1AuthorsId>>, { id: number; data: Author }> = (
    props,
  ) => {
    const { id, data } = props ?? {};

    return putApiV1AuthorsId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1AuthorsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1AuthorsId>>>;
export type PutApiV1AuthorsIdMutationBody = Author;
export type PutApiV1AuthorsIdMutationError = AxiosError<unknown>;

export const usePutApiV1AuthorsId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1AuthorsId>>,
      TError,
      { id: number; data: Author },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof putApiV1AuthorsId>>, TError, { id: number; data: Author }, TContext> => {
  return useMutation(getPutApiV1AuthorsIdMutationOptions(options), queryClient);
};

export const deleteApiV1AuthorsId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/Authors/${id}`, options);
};

export const getDeleteApiV1AuthorsIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteApiV1AuthorsId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteApiV1AuthorsId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1AuthorsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>>;

export type DeleteApiV1AuthorsIdMutationError = AxiosError<unknown>;

export const useDeleteApiV1AuthorsId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>, TError, { id: number }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiV1AuthorsId>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteApiV1AuthorsIdMutationOptions(options), queryClient);
};

export const getApiV1Books = (options?: AxiosRequestConfig): Promise<AxiosResponse<Book[]>> => {
  return axios.default.get(`/api/v1/Books`, options);
};

export const getGetApiV1BooksQueryKey = () => {
  return [`/api/v1/Books`] as const;
};

export const getGetApiV1BooksQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Books>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1BooksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Books>>> = ({ signal }) =>
    getApiV1Books({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Books>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1BooksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Books>>>;
export type GetApiV1BooksQueryError = AxiosError<unknown>;

export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = AxiosError<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Books>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Books>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Books>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Books>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1Books<TData = Awaited<ReturnType<typeof getApiV1Books>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Books>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1BooksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiV1Books = (book: Book, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.post(`/api/v1/Books`, book, options);
};

export const getPostApiV1BooksMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError, { data: Book }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError, { data: Book }, TContext> => {
  const mutationKey = ["postApiV1Books"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Books>>, { data: Book }> = (props) => {
    const { data } = props ?? {};

    return postApiV1Books(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1BooksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Books>>>;
export type PostApiV1BooksMutationBody = Book;
export type PostApiV1BooksMutationError = AxiosError<unknown>;

export const usePostApiV1Books = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Books>>, TError, { data: Book }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiV1Books>>, TError, { data: Book }, TContext> => {
  return useMutation(getPostApiV1BooksMutationOptions(options), queryClient);
};

export const getApiV1BooksId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Book>> => {
  return axios.default.get(`/api/v1/Books/${id}`, options);
};

export const getGetApiV1BooksIdQueryKey = (id: number) => {
  return [`/api/v1/Books/${id}`] as const;
};

export const getGetApiV1BooksIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1BooksId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1BooksIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BooksId>>> = ({ signal }) =>
    getApiV1BooksId(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1BooksId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1BooksIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BooksId>>>;
export type GetApiV1BooksIdQueryError = AxiosError<unknown>;

export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = AxiosError<unknown>>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BooksId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BooksId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BooksId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1BooksId<TData = Awaited<ReturnType<typeof getApiV1BooksId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BooksId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1BooksIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiV1BooksId = (id: number, book: Book, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.put(`/api/v1/Books/${id}`, book, options);
};

export const getPutApiV1BooksIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1BooksId>>,
    TError,
    { id: number; data: Book },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof putApiV1BooksId>>, TError, { id: number; data: Book }, TContext> => {
  const mutationKey = ["putApiV1BooksId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1BooksId>>, { id: number; data: Book }> = (
    props,
  ) => {
    const { id, data } = props ?? {};

    return putApiV1BooksId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1BooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1BooksId>>>;
export type PutApiV1BooksIdMutationBody = Book;
export type PutApiV1BooksIdMutationError = AxiosError<unknown>;

export const usePutApiV1BooksId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1BooksId>>,
      TError,
      { id: number; data: Book },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof putApiV1BooksId>>, TError, { id: number; data: Book }, TContext> => {
  return useMutation(getPutApiV1BooksIdMutationOptions(options), queryClient);
};

export const deleteApiV1BooksId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/Books/${id}`, options);
};

export const getDeleteApiV1BooksIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteApiV1BooksId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1BooksId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteApiV1BooksId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1BooksIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1BooksId>>>;

export type DeleteApiV1BooksIdMutationError = AxiosError<unknown>;

export const useDeleteApiV1BooksId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError, { id: number }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiV1BooksId>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteApiV1BooksIdMutationOptions(options), queryClient);
};

export const getApiV1CoverPhotos = (options?: AxiosRequestConfig): Promise<AxiosResponse<CoverPhoto[]>> => {
  return axios.default.get(`/api/v1/CoverPhotos`, options);
};

export const getGetApiV1CoverPhotosQueryKey = () => {
  return [`/api/v1/CoverPhotos`] as const;
};

export const getGetApiV1CoverPhotosQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotos>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1CoverPhotosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CoverPhotos>>> = ({ signal }) =>
    getApiV1CoverPhotos({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1CoverPhotosQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CoverPhotos>>>;
export type GetApiV1CoverPhotosQueryError = AxiosError<unknown>;

export function useGetApiV1CoverPhotos<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotos<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotos<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotos>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1CoverPhotos<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotos>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotos>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1CoverPhotosQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiV1CoverPhotos = (
  coverPhoto: CoverPhoto,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CoverPhoto>> => {
  return axios.default.post(`/api/v1/CoverPhotos`, coverPhoto, options);
};

export const getPostApiV1CoverPhotosMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1CoverPhotos>>,
    TError,
    { data: CoverPhoto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CoverPhotos>>, TError, { data: CoverPhoto }, TContext> => {
  const mutationKey = ["postApiV1CoverPhotos"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CoverPhotos>>, { data: CoverPhoto }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return postApiV1CoverPhotos(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1CoverPhotosMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CoverPhotos>>>;
export type PostApiV1CoverPhotosMutationBody = CoverPhoto;
export type PostApiV1CoverPhotosMutationError = AxiosError<unknown>;

export const usePostApiV1CoverPhotos = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiV1CoverPhotos>>,
      TError,
      { data: CoverPhoto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiV1CoverPhotos>>, TError, { data: CoverPhoto }, TContext> => {
  return useMutation(getPostApiV1CoverPhotosMutationOptions(options), queryClient);
};

export const getApiV1CoverPhotosBooksCoversIdBook = (
  idBook: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CoverPhoto[]>> => {
  return axios.default.get(`/api/v1/CoverPhotos/books/covers/${idBook}`, options);
};

export const getGetApiV1CoverPhotosBooksCoversIdBookQueryKey = (idBook: number) => {
  return [`/api/v1/CoverPhotos/books/covers/${idBook}`] as const;
};

export const getGetApiV1CoverPhotosBooksCoversIdBookQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1CoverPhotosBooksCoversIdBookQueryKey(idBook);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>> = ({ signal }) =>
    getApiV1CoverPhotosBooksCoversIdBook(idBook, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!idBook, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1CoverPhotosBooksCoversIdBookQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>
>;
export type GetApiV1CoverPhotosBooksCoversIdBookQueryError = AxiosError<unknown>;

export function useGetApiV1CoverPhotosBooksCoversIdBook<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotosBooksCoversIdBook<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotosBooksCoversIdBook<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1CoverPhotosBooksCoversIdBook<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>,
  TError = AxiosError<unknown>,
>(
  idBook: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosBooksCoversIdBook>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1CoverPhotosBooksCoversIdBookQueryOptions(idBook, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getApiV1CoverPhotosId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<CoverPhoto>> => {
  return axios.default.get(`/api/v1/CoverPhotos/${id}`, options);
};

export const getGetApiV1CoverPhotosIdQueryKey = (id: number) => {
  return [`/api/v1/CoverPhotos/${id}`] as const;
};

export const getGetApiV1CoverPhotosIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1CoverPhotosIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>> = ({ signal }) =>
    getApiV1CoverPhotosId(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1CoverPhotosIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>>;
export type GetApiV1CoverPhotosIdQueryError = AxiosError<unknown>;

export function useGetApiV1CoverPhotosId<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotosId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotosId<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CoverPhotosId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1CoverPhotosId<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1CoverPhotosId<
  TData = Awaited<ReturnType<typeof getApiV1CoverPhotosId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CoverPhotosId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1CoverPhotosIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiV1CoverPhotosId = (
  id: number,
  coverPhoto: CoverPhoto,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<CoverPhoto>> => {
  return axios.default.put(`/api/v1/CoverPhotos/${id}`, coverPhoto, options);
};

export const getPutApiV1CoverPhotosIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1CoverPhotosId>>,
    TError,
    { id: number; data: CoverPhoto },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1CoverPhotosId>>,
  TError,
  { id: number; data: CoverPhoto },
  TContext
> => {
  const mutationKey = ["putApiV1CoverPhotosId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1CoverPhotosId>>,
    { id: number; data: CoverPhoto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiV1CoverPhotosId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1CoverPhotosIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1CoverPhotosId>>>;
export type PutApiV1CoverPhotosIdMutationBody = CoverPhoto;
export type PutApiV1CoverPhotosIdMutationError = AxiosError<unknown>;

export const usePutApiV1CoverPhotosId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1CoverPhotosId>>,
      TError,
      { id: number; data: CoverPhoto },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1CoverPhotosId>>,
  TError,
  { id: number; data: CoverPhoto },
  TContext
> => {
  return useMutation(getPutApiV1CoverPhotosIdMutationOptions(options), queryClient);
};

export const deleteApiV1CoverPhotosId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/CoverPhotos/${id}`, options);
};

export const getDeleteApiV1CoverPhotosIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteApiV1CoverPhotosId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>, { id: number }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteApiV1CoverPhotosId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1CoverPhotosIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>>;

export type DeleteApiV1CoverPhotosIdMutationError = AxiosError<unknown>;

export const useDeleteApiV1CoverPhotosId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiV1CoverPhotosId>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteApiV1CoverPhotosIdMutationOptions(options), queryClient);
};

export const getApiV1Users = (options?: AxiosRequestConfig): Promise<AxiosResponse<User[]>> => {
  return axios.default.get(`/api/v1/Users`, options);
};

export const getGetApiV1UsersQueryKey = () => {
  return [`/api/v1/Users`] as const;
};

export const getGetApiV1UsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Users>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Users>>> = ({ signal }) =>
    getApiV1Users({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Users>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1UsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Users>>>;
export type GetApiV1UsersQueryError = AxiosError<unknown>;

export function useGetApiV1Users<TData = Awaited<ReturnType<typeof getApiV1Users>>, TError = AxiosError<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Users<TData = Awaited<ReturnType<typeof getApiV1Users>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Users>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Users>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1Users<TData = Awaited<ReturnType<typeof getApiV1Users>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1Users<TData = Awaited<ReturnType<typeof getApiV1Users>>, TError = AxiosError<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1UsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const postApiV1Users = (user: User, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.post(`/api/v1/Users`, user, options);
};

export const getPostApiV1UsersMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError, { data: User }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError, { data: User }, TContext> => {
  const mutationKey = ["postApiV1Users"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1Users>>, { data: User }> = (props) => {
    const { data } = props ?? {};

    return postApiV1Users(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1UsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1Users>>>;
export type PostApiV1UsersMutationBody = User;
export type PostApiV1UsersMutationError = AxiosError<unknown>;

export const usePostApiV1Users = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postApiV1Users>>, TError, { data: User }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postApiV1Users>>, TError, { data: User }, TContext> => {
  return useMutation(getPostApiV1UsersMutationOptions(options), queryClient);
};

export const getApiV1UsersId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/v1/Users/${id}`, options);
};

export const getGetApiV1UsersIdQueryKey = (id: number) => {
  return [`/api/v1/Users/${id}`] as const;
};

export const getGetApiV1UsersIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1UsersId>>,
  TError = AxiosError<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersId>>> = ({ signal }) =>
    getApiV1UsersId(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1UsersId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1UsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1UsersId>>>;
export type GetApiV1UsersIdQueryError = AxiosError<unknown>;

export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = AxiosError<unknown>>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1UsersId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetApiV1UsersId<TData = Awaited<ReturnType<typeof getApiV1UsersId>>, TError = AxiosError<unknown>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersId>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiV1UsersIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const putApiV1UsersId = (id: number, user: User, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.put(`/api/v1/Users/${id}`, user, options);
};

export const getPutApiV1UsersIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1UsersId>>,
    TError,
    { id: number; data: User },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof putApiV1UsersId>>, TError, { id: number; data: User }, TContext> => {
  const mutationKey = ["putApiV1UsersId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1UsersId>>, { id: number; data: User }> = (
    props,
  ) => {
    const { id, data } = props ?? {};

    return putApiV1UsersId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1UsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1UsersId>>>;
export type PutApiV1UsersIdMutationBody = User;
export type PutApiV1UsersIdMutationError = AxiosError<unknown>;

export const usePutApiV1UsersId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiV1UsersId>>,
      TError,
      { id: number; data: User },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof putApiV1UsersId>>, TError, { id: number; data: User }, TContext> => {
  return useMutation(getPutApiV1UsersIdMutationOptions(options), queryClient);
};

export const deleteApiV1UsersId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/Users/${id}`, options);
};

export const getDeleteApiV1UsersIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersId>>, TError, { id: number }, TContext> => {
  const mutationKey = ["deleteApiV1UsersId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV1UsersId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteApiV1UsersId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1UsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV1UsersId>>>;

export type DeleteApiV1UsersIdMutationError = AxiosError<unknown>;

export const useDeleteApiV1UsersId = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteApiV1UsersId>>, TError, { id: number }, TContext>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteApiV1UsersId>>, TError, { id: number }, TContext> => {
  return useMutation(getDeleteApiV1UsersIdMutationOptions(options), queryClient);
};
