/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export interface Activity {
  id?: number;
  /** @nullable */
  title?: string | null;
  dueDate?: string;
  completed?: boolean;
}
