/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export interface Book {
  id?: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  pageCount?: number;
  /** @nullable */
  excerpt?: string | null;
  publishDate?: string;
}
