/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export interface CoverPhoto {
  id?: number;
  idBook?: number;
  /** @nullable */
  url?: string | null;
}
