/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export * from "./activity";
export * from "./author";
export * from "./book";
export * from "./coverPhoto";
export * from "./user";
