/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */

export interface User {
  id?: number;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  password?: string | null;
}
