// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zActivity = z.object({
  id: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  title: z.optional(z.union([z.string(), z.null()])),
  dueDate: z.optional(z.iso.datetime()),
  completed: z.optional(z.boolean()),
});

export const zAuthor = z.object({
  id: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  idBook: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  firstName: z.optional(z.union([z.string(), z.null()])),
  lastName: z.optional(z.union([z.string(), z.null()])),
});

export const zBook = z.object({
  id: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  title: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  pageCount: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  excerpt: z.optional(z.union([z.string(), z.null()])),
  publishDate: z.optional(z.iso.datetime()),
});

export const zCoverPhoto = z.object({
  id: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  idBook: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  url: z.optional(z.union([z.url(), z.null()])),
});

export const zUser = z.object({
  id: z.optional(
    z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  ),
  userName: z.optional(z.union([z.string(), z.null()])),
  password: z.optional(z.union([z.string(), z.null()])),
});

export const zGetApiV1ActivitiesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1ActivitiesResponse = z.array(zActivity);

export const zPostApiV1ActivitiesData = z.object({
  body: z.optional(zActivity),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPostApiV1ActivitiesResponse = zActivity;

export const zDeleteApiV1ActivitiesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1ActivitiesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1ActivitiesByIdResponse = zActivity;

export const zPutApiV1ActivitiesByIdData = z.object({
  body: z.optional(zActivity),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPutApiV1ActivitiesByIdResponse = zActivity;

export const zGetApiV1AuthorsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1AuthorsResponse = z.array(zAuthor);

export const zPostApiV1AuthorsData = z.object({
  body: z.optional(zAuthor),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPostApiV1AuthorsResponse = zAuthor;

export const zGetApiV1AuthorsAuthorsBooksByIdBookData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    idBook: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1AuthorsAuthorsBooksByIdBookResponse = z.array(zAuthor);

export const zDeleteApiV1AuthorsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1AuthorsByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1AuthorsByIdResponse = zAuthor;

export const zPutApiV1AuthorsByIdData = z.object({
  body: z.optional(zAuthor),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPutApiV1AuthorsByIdResponse = zAuthor;

export const zGetApiV1BooksData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1BooksResponse = z.array(zBook);

export const zPostApiV1BooksData = z.object({
  body: z.optional(zBook),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiV1BooksByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1BooksByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1BooksByIdResponse = zBook;

export const zPutApiV1BooksByIdData = z.object({
  body: z.optional(zBook),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1CoverPhotosData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1CoverPhotosResponse = z.array(zCoverPhoto);

export const zPostApiV1CoverPhotosData = z.object({
  body: z.optional(zCoverPhoto),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPostApiV1CoverPhotosResponse = zCoverPhoto;

export const zGetApiV1CoverPhotosBooksCoversByIdBookData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    idBook: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1CoverPhotosBooksCoversByIdBookResponse = z.array(zCoverPhoto);

export const zDeleteApiV1CoverPhotosByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1CoverPhotosByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1CoverPhotosByIdResponse = zCoverPhoto;

export const zPutApiV1CoverPhotosByIdData = z.object({
  body: z.optional(zCoverPhoto),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zPutApiV1CoverPhotosByIdResponse = zCoverPhoto;

export const zGetApiV1UsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Success
 */
export const zGetApiV1UsersResponse = z.array(zUser);

export const zPostApiV1UsersData = z.object({
  body: z.optional(zUser),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zDeleteApiV1UsersByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zGetApiV1UsersByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});

export const zPutApiV1UsersByIdData = z.object({
  body: z.optional(zUser),
  path: z.object({
    id: z
      .int()
      .min(-2147483648, { error: "Invalid value: Expected int32 to be >= -2147483648" })
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
  }),
  query: z.optional(z.never()),
});
