/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * FakeRESTApi.Web V1
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1ActivitiesIdParams = zod.object({
  id: zod.number(),
});

export const PutApiV1ActivitiesIdParams = zod.object({
  id: zod.number(),
});

export const DeleteApiV1ActivitiesIdParams = zod.object({
  id: zod.number(),
});

export const GetApiV1AuthorsAuthorsBooksIdBookParams = zod.object({
  idBook: zod.number(),
});

export const GetApiV1AuthorsIdParams = zod.object({
  id: zod.number(),
});

export const PutApiV1AuthorsIdParams = zod.object({
  id: zod.number(),
});

export const DeleteApiV1AuthorsIdParams = zod.object({
  id: zod.number(),
});

export const GetApiV1BooksIdParams = zod.object({
  id: zod.number(),
});

export const PutApiV1BooksIdParams = zod.object({
  id: zod.number(),
});

export const DeleteApiV1BooksIdParams = zod.object({
  id: zod.number(),
});

export const GetApiV1CoverPhotosBooksCoversIdBookParams = zod.object({
  idBook: zod.number(),
});

export const GetApiV1CoverPhotosIdParams = zod.object({
  id: zod.number(),
});

export const PutApiV1CoverPhotosIdParams = zod.object({
  id: zod.number(),
});

export const DeleteApiV1CoverPhotosIdParams = zod.object({
  id: zod.number(),
});

export const GetApiV1UsersIdParams = zod.object({
  id: zod.number(),
});

export const PutApiV1UsersIdParams = zod.object({
  id: zod.number(),
});

export const DeleteApiV1UsersIdParams = zod.object({
  id: zod.number(),
});
